### PR TITLE
docs: add versions of default plugins and components used by kubekey

### LINKED ISSUE #1433: document to show versions of plugins and components
### Your current KubeKey version

_No response_

### Describe this feature

like **calico** which default version information is in [apis/kubekey/v1alpha1/default.go](https://github.com/kubesphere/kubekey/blob/986449b5790df0928fff9605bd885c9836db622c/apis/kubekey/v1alpha1/default.go#L43) instead of a document , so have a document to show versions of plugins and components used by kubekey can help users troubleshoot version compatibility issues more easily

### Describe the solution you'd like

add file in kubekey/docs/

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xiaods**
fix issue #1433

Signed-off-by: Deshi Xiao <xiaods@gmail.com>

### What type of PR is this?
/kind documentation

### What this PR does / why we need it:

quote from request "like calico which default version information is in [apis/kubekey/v1alpha1/default.go](https://github.com/kubesphere/kubekey/blob/986449b5790df0928fff9605bd885c9836db622c/apis/kubekey/v1alpha1/default.go#L43) instead of a document , so have a document to show versions of plugins and components used by kubekey can help users troubleshoot version compatibility issues more easily"

this changed based on  [v1alpha2](https://github.com/kubesphere/kubekey/blob/master/cmd/kk/apis/kubekey/v1alpha2/default.go).

### Which issue(s) this PR fixes:

Fixes #1433 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by 24sama** [comment]
Thanks @xiaods , but I guess you need to follow the [v1alpha2](https://github.com/kubesphere/kubekey/blob/master/cmd/kk/apis/kubekey/v1alpha2/default.go) not v1alpha1.

**Comment by xiaods** [comment]
> Thanks @xiaods , but I guess you need to follow the [v1alpha2](https://github.com/kubesphere/kubekey/blob/master/cmd/kk/apis/kubekey/v1alpha2/default.go) not v1alpha1.

yes, it already based on [v1alpha2](https://github.com/kubesphere/kubekey/blob/master/cmd/kk/apis/kubekey/v1alpha2/default.go).  please give a review  @24sama

**Comment by 24sama** [comment]
@all-contributors please add @xiaods for code, doc

**Pull request merged**
