### PR TITLE
feat:add k8e install pipeline

### PR DESCRIPTION
**Pull request by xiaods**
Support for deploying k8e #1359

Signed-off-by: Xiao Deshi <xiaods@gmail.com>

### What type of PR is this?
/kind feature

### What this PR does / why we need it:
k8e - Simple Enterprise Kubernetes. I would like to adopt more enterprise features in a lightweight distribution, a binary component, k8e to provide all the k8s components.

it solid on enterprise LTS version

create cluster:
```
./bin/linux/amd64/kk create cluster --with-kubernetes v1.21.14-k8e
```
delete cluster:
```
./bin/linux/amd64/kk delete cluster --with-kubernetes v1.21.14-k8e
```
### Which issue(s) this PR fixes:

 Feat  Request #1359

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
Add new Simple Enterprise Kubernetes distribution to kk. 
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by 24sama** [comment]
Thanks for your contributions! It's very COOL!

**Comment by xiaods** [comment]
> Thanks for your contributions! It's very COOL!

any feedback?

**Comment by 24sama** [comment]
> > Thanks for your contributions! It's very COOL!
> 
> any feedback?

Sorry for the late reply to you, may take some time to review this PR caused I'm busy recently.

**Comment by xiaods** [comment]
> > > Thanks for your contributions! It's very COOL!
> > 
> > 
> > any feedback?
> 
> Sorry for the late reply to you, may take some time to review this PR caused I'm busy recently.

don't worry. let it go

**Pull request merged**
