### PR TITLE
add manifest and artifact en doc

### PR DESCRIPTION
**Pull request by 24sama**
### What type of PR is this?

/kind documentation

### What this PR does / why we need it:
add manifest and artifact en doc

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Patrick-LuoYu** [comment]
Maybe we do not need to introduce the `artifact` and `manifest` concepts, which are difficult to understand for new users. Just call them `offline installation package` and `offline installation package configuration file`.

**Comment by 24sama** [comment]
> Maybe we do not need to introduce the `artifact` and `manifest` concepts, which are difficult to understand for new users. Just call them `offline installation package` and `offline installation package configuration file`.

You're the definition of the `artifact` and `manifest` is correct. But the `artifact` and `manifest` is already a specific field (or a feature?) of the KubeKey, just like the `pod` of Kubernetes. So I want to explain and define these fields as much as possible and have the user accept them as if they were the `pod`.

**Comment by FeynmanZhou** [comment]
> > Maybe we do not need to introduce the `artifact` and `manifest` concepts, which are difficult to understand for new users. Just call them `offline installation package` and `offline installation package configuration file`.
> 
> You're the definition of the `artifact` and `manifest` is correct. But the `artifact` and `manifest` is already a specific field (or a feature?) of the KubeKey, just like the `pod` of Kubernetes. So I want to explain and define these fields as much as possible and have the user accept them as if they were the `pod`.

IMO, `artifact` and `manifest` are very commonly used in the cloud-native area, can we add a glossary part for KubeKey to explain those definitions?

**Comment by Patrick-LuoYu** [comment]
Manifest should not be used as the name of a feature. It is a general word, and any configuration file can be called a manifest. Naming a feature `manifest` is like naming the feature `configuration file`, or naming fruits of a tree `fruit`. Kubernetes names one of its resource category `pod` because it adds meaning to the ordinary word `pod`. The meaning of the word `pod` in the context of Kubernetes is different from the common meanings of `pod`. However, in the context of KubeKey, a manifest is a configuration file, the same as its original meaning, nothing else.

**Comment by 24sama** [comment]
> > > Maybe we do not need to introduce the `artifact` and `manifest` concepts, which are difficult to understand for new users. Just call them `offline installation package` and `offline installation package configuration file`.
> > 
> > 
> > You're the definition of the `artifact` and `manifest` is correct. But the `artifact` and `manifest` is already a specific field (or a feature?) of the KubeKey, just like the `pod` of Kubernetes. So I want to explain and define these fields as much as possible and have the user accept them as if they were the `pod`.
> 
> IMO, `artifact` and `manifest` are very commonly used in the cloud-native area, can we add a glossary part for KubeKey to explain those definitions?

Looks good to me.

**Comment by Patrick-LuoYu** [comment]
To be more clear, using `manifest` as the name of a KubeKey feature is like naming a newborn kid `human`. The word `human` should not be the name of anyone. There is a great difference between general words and terms.

**Comment by Patrick-LuoYu** [comment]
If you name this KubeKey feature `manifest`, how do you explain the concept `manifest`? A `manifest` is a configuration file used to create an offline installation package? This is the same as "A human is a man born in California", which is non-sense. A human is any man and woman on the Earth, not specific to man and California.

**Comment by 24sama** [comment]
> To be more clear, using `manifest` as the name of a KubeKey feature is like naming a newborn kid `human`. The word `human` should not be the name of anyone. There is a great difference between general words and terms.

You're right. I agree with you. So, should I remove the `artifact` and `manifest` description paragraphs? And call them offline installation package and offline installation package configuration file.

**Comment by Patrick-LuoYu** [comment]
Just call them `offline installation package` and `offline installation package configuration file`. Everybody knows what they are. You don't even need to explain them.

**Comment by 24sama** [comment]
> Just call them `offline installation package` and `offline installation package configuration file`. Everybody knows what they are. You don't even need to explain them.

OK, I will change it later.

**Comment by Patrick-LuoYu** [comment]
If you think `offline installation package` and `offline installation package configuration file` are too long, you can call them `offline package` and `offline package configuration file` with explanation that the offline package is used to install Kubernetes in an offline environment.

**Comment by 24sama** [comment]
@Patrick-LuoYu 
I make some updates, PTAL.

**Pull request merged**
