### PR TITLE
fix: remove syncKubeConfigToWorker with strict security concerns

### LINKED ISSUE #1663: Why do you add kubectl and kube config on all worker nodes?
### What is version of KubeKey has the issue?

2.2.2

### What is your os environment?

debian 11.5

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: debian-master, address: 192.168.101.154, internalAddress: 192.168.101.154, user: root, password: "123", timeout: 60}
  - {name: debian-worker-1, address: 192.168.101.155, internalAddress: 192.168.101.155, user: angelo, password: "123", timeout: 60}
  - {name: debian-worker-2, address: 192.168.101.156, internalAddress: 192.168.101.156, user: angelo, password: "123", timeout: 60}
  - {name: debian-worker-3, address: 192.168.101.157, internalAddress: 192.168.101.157, user: angelo, password: "123", timeout: 60}
  roleGroups:
    etcd:
    - debian-master
    control-plane:
    - debian-master
    worker:
    - debian-worker-1
    - debian-worker-2
    - debian-worker-3
  controlPlaneEndpoint:
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.24.1
    clusterName: cluster.local
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
    proxyMode: ipvs
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubeadm
  network:
    plugin: calico
    calico:
      ipipMode: Never
      vxlanMode: Never
      vethMTU: 1440
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

Why do you add kubectl and kube config on all worker nodes? 
When kubekey do installation it adds kubectl and kube config on all worker nodes. I understand why it needs on masters but why it needs on workers i don`t understand i think it is like security bug of installation

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xiaods**
* kubeconfig is only for ops user, worker node don't need kubeconfig

Signed-off-by: Deshi Xiao <xiaods@gmail.com>

### What type of PR is this?

/kind bug

### Which issue(s) this PR fixes:

Fixes #1663

### Special notes for reviewers:
User feedback:
When kubekey do installation it adds kubectl and kube config on all worker nodes. I understand why it needs on masters but why it needs on workers i don`t understand i think it is like security bug of installation

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pixiake** [comment]
The reason why kubeconfig is synchronized to each node is that many cluster operation managers sometimes need to go to the worker node to do some troubleshooting. It will be much more convenient to have kubeconfig.
In addition, the task `AddWorkerLabel` is performed on each node, and this task also depends on `kubeconfig`.

**Comment by xiaods** [comment]
> 

Thanks for explaining the principle of this, Ops operations should really only exist in the master node, even if the Node is tagged, it should be operated in the master node

**Comment by xiaods** [comment]
@pixiake I read the AddWorkerLabel, in default behavior is add worker lable to all node, just do this task on master is ok. please double check the logic and review the effective.

**Comment by xiaods** [comment]
any udpate?

**Comment by Nello-Angelo** [comment]
if a hacker gets on a worker node with an admin config, then user data will be in danger, it's bad practice to add config to workers and the kubectl utility too

**Comment by Nello-Angelo** [comment]
if you need this method, so, you can add a new method which delete kubeconfig, helm, kubectl and kubeadm on workers

**Comment by xiaods** [comment]
@24sama any comments?

**Comment by Nello-Angelo** [comment]
can you explane?

**Comment by 24sama** [comment]
Sorry to reply late. It's a very common feature-request.

But, IMO, I think this PR need to do more tests and maybe a little troublesome to the newbie user.

And I found here a PR, and it supports kk to run a customized shell script. Maybe we can use it to run a remove-kubeconfig-file script after creating a cluster.
https://github.com/kubesphere/kubekey/pull/1545

**Comment by Nello-Angelo** [comment]
you must to delete kubeconfig, helm, kubectl and kubeadm on workers. This cli needn`t on workers. Why do you install this helm, kubectl and kubeadm on workers ?

**Comment by xiaods** [comment]
> The reason why kubeconfig is synchronized to each node is that many cluster operation managers sometimes need to go to the worker node to do some troubleshooting. It will be much more convenient to have kubeconfig.
> In addition, the task `AddWorkerLabel` is performed on each node, and this task also depends on `kubeconfig`.

@Nello-Angelo  here is reason on keep kubeconfig on node.  in my patch I have resolved the addition task `AddWorkerLabel` on master node. could you please testing this patch on your server.

we need more testing on this patch, the result will prove the patch is correct.

**Comment by Nello-Angelo** [comment]
@xiaods what ref with changes?

**Comment by Nello-Angelo** [comment]
@xiaods and how does your patch work?

**Comment by xiaods** [comment]
> @xiaods what ref with changes and how does your patch work?

need your apply the pr and build a binary to test. I have no resource to verify this case.

**Comment by Nello-Angelo** [comment]
@xiaods give me the link with changes

**Comment by xiaods** [comment]
> @xiaods give me the link with changes

```
git clone -b fix-kubeconfig-sync-worker https://github.com/xiaods/kubekey.git
cd kubekey
make kk
```
then you will got the patched kk binary

**Comment by xiaods** [comment]
@Nello-Angelo waiting for your feedback.

**Comment by Nello-Angelo** [comment]
@xiaods as i understood your patched kk binary is working

[result of find on worker and master2.txt](https://github.com/kubesphere/kubekey/files/10776855/result.of.find.on.worker.and.master2.txt)

[output of installation on debian 11.txt](https://github.com/kubesphere/kubekey/files/10776856/output.of.installation.on.debian.11.txt)

**Comment by Nello-Angelo** [comment]
@xiaods but you also need to remove kubectl and helm on the workers because those nodes are missing kubeconfig.
You won't be able to use kubectl and helm

**Comment by xiaods** [comment]
@Nello-Angelo sadly the SyncKubeBinaries is run once func, I can't split the step to sub step. for your concerns, need another request issue to handle. this pr only handle kubeconfig and nodelabel patch issue.

**Comment by xiaods** [comment]
@24sama  with testing logs. the behaviors is consistent by design. please review again.

**Comment by xiaods** [comment]
@Nello-Angelo today i review the code and give some tune on add worker label command. if you have some time, cloud you please double check the patch. thanks for concerns.

**Comment by Nello-Angelo** [comment]
@xiaods i checked your patch and cluster works correct and i couldn`t find the kubeconfig on workers.
so it works correct

**Comment by Nello-Angelo** [comment]
@xiaods it works correct

[result of find.txt](https://github.com/kubesphere/kubekey/files/10817124/result.of.find.txt)

**Comment by xiaods** [comment]
@Nello-Angelo thanks for your verify.

@pixiake @24sama  with testing confirmed, please double review the patch. it will resolve potential security on node.

**Comment by xiaods** [comment]
any update ?

**Comment by xiaods** [comment]
@pixiake  you said: the task AddWorkerLabel is performed on each node, and this task also depends on kubeconfig.
it can execute on master node, don't need on every node to perform the command.

**Comment by Nello-Angelo** [comment]
@pixiake guy please answer

**Comment by xiaods** [comment]
> @pixiake you said: the task AddWorkerLabel is performed on each node, and this task also depends on kubeconfig. it can execute on master node, don't need on every node to perform the command.

any advice on my patch, I can finetune this patch.

**Comment by xiaods** [comment]
> And I found here a PR, and it supports kk to run a customized shell script. Maybe we can use it to run a remove-kubeconfig-file script after creating a cluster.

Do you prefer to use external scripts to remove the kubeconfig file on the agent node? I don't think we need that here. You can check my submitted code, where we can label the agent nodes from the master node without any impact from previous operations. Currently, there is only one requirement: if an administrator wants to operate on the k8s cluster on an agent, they will need a kubeconfig file. However, this habit is not secure or user-friendly. Please reconsider it again. Thank you.

**Comment by xiaods** [comment]
welcome any suggest on this PR. @pixiake @24sama , I am welcome any suggest on this pr.

**Comment by xiaods** [comment]
any update?

**Comment by pixiake** [comment]
I'm sorry for not responding in time. Distributing kubeconfig to each node does have security risks, and I believe this patch can be merged.
@xiaods @Nello-Angelo Thanks for your contribution and testing.

**Comment by pixiake** [comment]
@xiaods This patch may also need to be considered the following:
1. `ConfigureKubernetesModule` also uses kubectl on each node.
https://github.com/kubesphere/kubekey/blob/6464406d61c2f47c5e334181fab4f6116e566441/cmd/kk/pkg/kubernetes/module.go#L589
https://github.com/kubesphere/kubekey/blob/6464406d61c2f47c5e334181fab4f6116e566441/cmd/kk/pkg/kubernetes/tasks.go#L1071

2. I found that you changed the logic of labeling nodes to add  `node-role.kubernetes.io/worker=`  only when there is no `node-role.kubernetes.io/master=`, but I think `node-role.kubernetes.io/worker=` should also be add for master nodes that are added to the worker group by users in the configuration file.

**Comment by xiaods** [comment]
> 2\. worker group by users in the configuration file.

I will update it asap.

**Comment by xiaods** [comment]
> @xiaods This patch may also need to be considered the following:
> 
> 1. `ConfigureKubernetesModule` also uses kubectl on each node.
>    https://github.com/kubesphere/kubekey/blob/6464406d61c2f47c5e334181fab4f6116e566441/cmd/kk/pkg/kubernetes/module.go#L589
>    
>    https://github.com/kubesphere/kubekey/blob/6464406d61c2f47c5e334181fab4f6116e566441/cmd/kk/pkg/kubernetes/tasks.go#L1071
> 2. I found that you changed the logic of labeling nodes to add  `node-role.kubernetes.io/worker=`  only when there is no `node-role.kubernetes.io/master=`, but I think `node-role.kubernetes.io/worker=` should also be add for master nodes that are added to the worker group by users in the configuration file.

@pixiake update patch for below issue:
 1. `ConfigureKubernetesModule` also uses kubectl on each node.   ---->  done.
 2. I found that you changed the logic of labeling nodes to add  `node-role.kubernetes.io/worker=`  only when there is no `node-role.kubernetes.io/master=`, but I think `node-role.kubernetes.io/worker=` should also be add for master nodes that are added to the worker group by users in the configuration file.   ------> done
 
 please review the code, thanks for your guide.

**Comment by xiaods** [comment]
any update? @pixiake @24sama

**Comment by pixiake** [comment]
@all-contributors please add @Nello-Angelo for ideas

**Pull request merged**
