### PR TITLE
Experiment: support more network plugin and modify task result

### PR DESCRIPTION
**Pull request by 24sama**
* CNI supports flannel and Cilium 
* make task result display each to each

### CODE REVIEW

**Comment by xmulligan** [comment]
@24sama Glad to see that you now support Cilium? Would you mind adding Kubekey to the Cilium adopters list? https://github.com/cilium/cilium/blob/master/USERS.md

We need this for when we apply to graduate at the CNCF

**Comment by FeynmanZhou** [comment]
> @24sama Glad to see that you now support Cilium? Would you mind adding Kubekey to the Cilium adopters list? https://github.com/cilium/cilium/blob/master/USERS.md
> 
> We need this for when we apply to graduate at the CNCF

Hi @xmulligan 

Yes, KubeKey has integrated Cilium. You can check out this [blog post](https://kubesphere.io/blogs/cilium-as-cni/) for details. I could raise a PR to add KubeKey as an adopter of Cilium : )

**Comment by xmulligan** [comment]
@FeynmanZhou That would be great if you create that PR! Do you mind if we also link to the blog on our website?

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou That would be great if you create that PR! Do you mind if we also link to the blog on our website?

It's a good idea.

**Comment by xmulligan** [comment]
@FeynmanZhou we just added it to the blog in https://github.com/cilium/cilium.io/pull/10. Can you add Kubekey to the adopters list?

**Comment by FeynmanZhou** [comment]
> https://github.com/cilium/cilium.io/pull/10

@xmulligan 
Yes, thanks for letting us know. I will add it to the ADOPTERS list when I get back to the office tomorrow morning.

**Comment by FeynmanZhou** [comment]
> > https://github.com/cilium/cilium.io/pull/10
> 
> @xmulligan Yes, thanks for letting us know. I will add it to the ADOPTERS list when I get back to the office tomorrow morning.
@xmulligan 
See : https://github.com/cilium/cilium/pull/18937

**Pull request merged**
