### PR TITLE
Change externalElasticsearchUrl to externalElasticsearchHost at cc

### PR DESCRIPTION
**Pull request by mangoGoForward**
### What this PR dose?
Change externalElasticsearchUrl to externalElasticsearchHost at cc, and make the definition more clear.

### What this PR does / why we need it:
please see kubesphere/kubesphere#3829.

### Which issue(s) this PR fixes:

Fixes kubesphere/kubesphere#3829.

### CODE REVIEW

**Comment by 24sama** [comment]
Thanks for your contribution! I will approve this PR when other refer PRs have been merged.

**Comment by mangoGoForward** [comment]
> Thanks for your contribution! I will approve this PR when other refer PRs have been merged.

Ok.

**Comment by 24sama** [comment]
@mangoGoForward Hi!
Sorry, my mistake. The old version may not support this field including KubeSphere v3.2.0, and more detail is [here](https://github.com/kubesphere/helm-charts/pull/185#issuecomment-962969985).
So, i will revert this PR.

**Comment by mangoGoForward** [comment]
> @mangoGoForward Hi! Sorry, my mistake. The old version may not support this field including KubeSphere v3.2.0, and more detail is [here](https://github.com/kubesphere/helm-charts/pull/185#issuecomment-962969985). So, i will revert this PR.

Ok.

**Comment by 24sama** [comment]
@mangoGoForward 
I'm really appreciate for your contribution. I already create a revert PR for this PR, you don't need to do anything. And I create a issue(#751) to follow this change.

**Pull request merged**
