### PR TITLE
docs: Update kk upgrade parameters

### PR DESCRIPTION
**Pull request by lvillis**

### CODE REVIEW

**Comment by 24sama** [comment]
Thanks for your contribution.

Could you please also modify [these](https://github.com/kubesphere/kubekey#multi-nodes) error full name parameters?

**Comment by lvillis** [comment]
> Thanks for your contribution.
> 
> Could you please also modify [these](https://github.com/kubesphere/kubekey#multi-nodes) error full name parameters?

Now all "--file" parameters have been updated to "--filename"

**Comment by 24sama** [comment]
> > Thanks for your contribution.
> > Could you please also modify [these](https://github.com/kubesphere/kubekey#multi-nodes) error full name parameters?
> 
> Now all "--file" parameters have been updated to "--filename"

Thanks.

/lgtm
/approve

**Comment by 24sama** [comment]
@allcontributors please add @lvillis for doc

**Pull request merged**
