### PR TITLE
Support Kubernetes 1.23

### PR DESCRIPTION
**Pull request by chaunceyjiang**

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
add `v1.23.0` to `SupportedK8sVersionList`
fix pr #887

**Comment by 24sama** [comment]
Thanks very much! And the last thing, maybe the [doc](https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md) needs to update.

**Comment by chaunceyjiang** [comment]
> Thanks very much! And the last thing, maybe the [doc](https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md) needs to update.

Isn't this file modified only when `kk` is released?

**Comment by 24sama** [comment]
Feel free. This file is just like the others.

**Comment by chaunceyjiang** [comment]
> Feel free. This file is just like the others.

ok

**Pull request merged**
