### PR TITLE
Support custom dnsDomain for cluster

### PR DESCRIPTION
**Pull request by pixiake**
### What does this PR do?
Support custom `dnsDomain` for cluster.

Signed-off-by: pixiake <guofeng@yunify.com>

### CODE REVIEW

**Comment by RolandMa1986** [comment]
@pixiake Do we need to change this function too?
https://github.com/kubesphere/kubekey/blob/88c26e54a1eb6b465c580c7f939480b62c021ea1/apis/kubekey/v1alpha2/cluster_types.go#L197

**Comment by pixiake** [comment]
> @pixiake Do we need to change this function too?
> 
> https://github.com/kubesphere/kubekey/blob/88c26e54a1eb6b465c580c7f939480b62c021ea1/apis/kubekey/v1alpha2/cluster_types.go#L197


Yes, it needs to be modified. I have changed it.

**Pull request merged**
