### PR TITLE
add v1alpha3 crd

### PR DESCRIPTION
**Pull request by 24sama**
### What type of PR is this?

/kind feature

### What this PR does / why we need it:
Add v1alpha3 crd

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lcfang** [comment]
why close this pr? @24sama Do we have any other plan?

**Comment by 24sama** [comment]
Hi @lcfang, thanks for your attention.
We plan to implement a cluster-api provider rather than totally implement a cluster-api. The source code is here: https://github.com/24sama/kubekey/tree/cluster-api-provider/exp

PR is in coming.

Are you interested in this feature?

**Comment by lcfang** [comment]
@24sama yes,I am interest this feature. I hope to participate in it. But I wonder the relationship between this feature and kk-operator, I have see a cluster-controller in source code, Is this feature a optimum proposal?

**Comment by 24sama** [comment]
We plan to combine cluster-api to enhance the capabilities of the kk operator. So as you see, kk operator may later be called `cluster-api-provider-kubekey`.

More information about cluster-api:
https://github.com/kubernetes-sigs/cluster-api
https://cluster-api.sigs.k8s.io/developer/providers/contracts.html

**Comment by pixiake** [comment]
> @24sama yes,I am interested in this feature. I hope to participate in it. But I wonder the relationship between this feature and kk-operator, I have see a cluster-controller in source code, Is this feature a optimum proposal?

For this feature, we will implement some basic functions rencently. Then we will make a list of follow-up tasks. At that time, you can choose the task you are interested in to participate in. Of course, you can always participate in community discussions if you have any ideas.

**Comment by lcfang** [comment]
> We plan to combine cluster-api to enhance the capabilities of the kk operator. So as you see, kk operator may later be called `cluster-api-provider-kubekey`. Their function is the same, i.e. to manage cluster nodes by the k8s CRD. In version v1alpha2, we only have a `Cluster` CRD, the level of abstraction is not sufficient. And about `cluster-api-provider-kubekey`, we follow the cluster-api guide to implement `KKCluster`, `KKMachine`, and `KKInstance`.
> 
> More information about cluster-api: https://github.com/kubernetes-sigs/cluster-api https://cluster-api.sigs.k8s.io/developer/providers/contracts.html

Yeah，I got it. Thanks for your reply.

> > @24sama yes,I am interested in this feature. I hope to participate in it. But I wonder the relationship between this feature and kk-operator, I have see a cluster-controller in source code, Is this feature a optimum proposal?
> 
> For this feature, we will implement some basic functions rencently. Then we will make a list of follow-up tasks. At that time, you can choose the task you are interested in to participate in. Of course, you can always participate in community discussions if you have any ideas.

WOW, I think it is a grate thing. I will keep an eye on this feature.

**Comment by 24sama** [comment]
Hi @lcfang , I guess you will be interested in this [PR](https://github.com/kubesphere/kubekey/pull/1421).

**Comment by wenwenxiong** [comment]
How to use it? cluster-api-provider-kubekey

**Comment by wenwenxiong** [comment]
does cluster-api-provider-kubekey support offline install k8s cluster?

**Comment by 24sama** [comment]
> does cluster-api-provider-kubekey support offline install k8s cluster?

Yeah, absolutely YES. But CAPKK is still in its early stages and lacks a lot of documentation. If you are interested in it, you can see more in: https://github.com/kubesphere/kubekey/tree/master/exp/cluster-api-provider-kubekey

**Pull request closed without merging**
