### PR TITLE
docs: instruction on kubeVip module invocation

### PR DESCRIPTION
**Pull request by lwabish**
### What type of PR is this?
/kind documentation

### What this PR does / why we need it:

add some code comments to avoid confusion, see #1689 

### Special notes for reviewers:

```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by 24sama** [comment]
Thanks for your contribution!

**Comment by 24sama** [comment]
@all-contributors please add @lwabish for code, doc

**Comment by lwabish** [comment]
Cool, Thanks! By the way, I got another kube-vip related bug working in progress.

**Pull request merged**
