### PR TITLE
Support Kubernetes 1.23

### LINKED ISSUE #864: Support Kubernetes 1.23
### Your current KubeKey version

1.2.0

### Describe this feature

As [Kubernetes 1.23 was released](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/) this week, I hope KubeKey could support the installation of Kubernetes 1.23. It would be better to support ARM 64bit and x86 64bit.

### Describe the solution you'd like

None

### Additional information

None

### PR DESCRIPTION
**Pull request by chaunceyjiang**
fix #864

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
```
 # kubectl version    
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
# kubectl get pods -A                                    
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
default       nginx-deployment2-9456bbbf9-7hstt          1/1     Running   0          31s
kube-system   calico-kube-controllers-64d69886fd-8qp8g   1/1     Running   0          2m33s
kube-system   calico-node-frb6r                          1/1     Running   0          2m34s
kube-system   coredns-7c94484977-6j46h                   1/1     Running   0          2m33s
kube-system   coredns-7c94484977-kg66n                   1/1     Running   0          2m33s
kube-system   kube-apiserver-chauncey                    1/1     Running   2          2m48s
kube-system   kube-controller-manager-chauncey           1/1     Running   2          2m48s
kube-system   kube-proxy-ftxs2                           1/1     Running   0          2m34s
kube-system   kube-scheduler-chauncey                    1/1     Running   7          2m47s
kube-system   nodelocaldns-lfvkg                         1/1     Running   0          2m34s
```

**Comment by pixiake** [comment]
Thanks very much for this contribution.

**Comment by pixiake** [comment]
@chaunceyjiang 
The version information of also needs to be added to this file. 
https://github.com/kubesphere/kubekey/blob/master/pkg/version/kubernetes/version_enum.go

I think you can modify the documents at the same time and submit a new pr. Thanks !

**Comment by chaunceyjiang** [comment]
> @chaunceyjiang The version information of also needs to be added to this file. https://github.com/kubesphere/kubekey/blob/master/pkg/version/kubernetes/version_enum.go
> 
> I think you can modify the documents at the same time and submit a new pr. Thanks !

ok

**Pull request merged**
