### PR TITLE
reduce the size of KubeKey artifact

### LINKED ISSUE #1139: Reduce the size of KubeKey artifact
### Your current KubeKey version

v2.0.0

### Describe this feature

At present, the KubeKey artifact contains images' `tar` files. This results in the inability to reuse the common image's layers and waste storage space. For example, a KubeKey artifact exported from a KubeSphere cluster will contain nearly 160 images, and the size of it will be 14 GB.

### Describe the solution you'd like

We can follow the OCI (Open Container Image Layout) standard for storing the images, and archive this OCI directory into the KubeKey artifact.

### Additional information
https://github.com/containers/image
https://github.com/containers/skopeo
_No response_

### PR DESCRIPTION
**Pull request by 24sama**
### What type of PR is this?

/kind feature
/kind api-change

### What this PR does / why we need it:
Reduce the size of the KubeKey artifact. This PR makes kk use [github.com/containers/image](https://github.com/containers/image) to pull images and store these images in OCI format. This allows, in a certain degree,  reuse of the base image layer. When we use kk to push images, the kk re-tag images as xxx-*arch*[*-variant*] (e.g. xxx-amd64, xxx-arm-v7) and also use this package to copy images to a private registry, after that the kk use [github.com/estesp/manifest-tool](https://github.com/estesp/manifest-tool) to push [manifest-lists](https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list) with the original tag of the images.

### Which issue(s) this PR fixes:

Fixes #1139

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?
**Breaking Change**
The next release of KubeKey could not support using the old KubeKey artifact.
Because of the change in image store format, the KubeKey artifact must be re-export by kk.

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liulangwa** [comment]
这个提交导致无法往http的镜像源推送镜像

```
error: Pipeline[ArtifactImagesPushPipeline] execute failed: Module[CopyImagesToRegistryModule] exec failed: 
failed: [LocalHost] [CopyImagesToRegistry] exec failed after 1 retires: copy image oci:/alex/kubekey/images:kubesphereio:cni:v3.23.2-amd64 to docker://docker.xxx.cn:60001/kube-vnet/kubesphereio/cni:v3.23.2-amd64 failed: trying to reuse blob sha256:a33c29efa196200d3373d4a355138a10786be4a6db0baac21553064cdc30f79a at destination: pinging container registry docker.ctyun.cn:60001: Get "https://docker.ctyun.cn:60001/v2/": http: server gave HTTP response to HTTPS client

```

**Comment by 24sama** [comment]
> 这个提交导致无法往http的镜像源推送镜像
> 
> 
> 
> ```
> 
> kk artifact image push -f config-ks.yaml -y
> 
> 
> 
> error: Pipeline[ArtifactImagesPushPipeline] execute failed: Module[CopyImagesToRegistryModule] exec failed: 
> 
> failed: [LocalHost] [CopyImagesToRegistry] exec failed after 1 retires: copy image oci:/alex/kubekey/images:kubesphereio:cni:v3.23.2-amd64 to docker://docker.xxx.cn:60001/kube-vnet/kubesphereio/cni:v3.23.2-amd64 failed: trying to reuse blob sha256:a33c29efa196200d3373d4a355138a10786be4a6db0baac21553064cdc30f79a at destination: pinging container registry docker.ctyun.cn:60001: Get "https://docker.ctyun.cn:60001/v2/": http: server gave HTTP response to HTTPS client
> 
> 
> 
> ```

I guess you maybe used the old configure method cause this PR is a breaking changes. 
Here is the latest:
```

registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: ""
    namespaceOverride: ""
    auths: # if docker add by `docker login`, if containerd append to `/etc/containerd/config.toml`
      "dockerhub.kubekey.local":
        username: "xxx"
        password: "***"
        skipTLSVerify: false # Allow contacting registries over HTTPS with failed TLS verification.
        plainHTTP: false # Allow contacting registries over HTTP.
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local" 
```

**Pull request merged**
