### PR TITLE
dev-v2.0.0: fix a kube config file owner bug

### PR DESCRIPTION
**Pull request by 24sama**
### What does this PR do?
* fix a kube config file ownner bug
* fix a tar file that extracts to a wrong dir bug

### CODE REVIEW

**Comment by pixiake** [comment]
I think it needs to be modified here, too.

https://github.com/kubesphere/kubekey/blob/f960dcff0bdaaf8c624afc8f2634016dd165951d/pkg/k3s/tasks.go#L116

**Comment by 24sama** [comment]
> I think it needs to be modified here, too.
> 
> https://github.com/kubesphere/kubekey/blob/f960dcff0bdaaf8c624afc8f2634016dd165951d/pkg/k3s/tasks.go#L116

Ok, done.

**Pull request merged**
