### PR TITLE
Remove zombie process crontab

### PR DESCRIPTION
**Pull request by yuzhiquan**
### What type of PR is this?

/kind bug

### What this PR does / why we need it:
Remove zombie process crontab, in some situation, this cron will kill dockershim and make pod recreated
### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
NONE
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pixiake** [comment]
Can you describe the situation in detail? Thanks
`dockershim` was killed by this cronjob, is it because the docker service is not normal?

**Comment by yuzhiquan** [comment]
> Can you describe the situation in detail? Thanks `dockershim` was killed by this cronjob, is it because the docker service is not normal?

If some pod in cluster create zombie process,and doesnot handle it,  then grep ppid will lead to the dockershim process, that's happening in our online cluster!

**Comment by pixiake** [comment]
> dockershim

Can we get around it by adding filter conditions to this command? 
such as: `ps -A -ostat,ppid,cmd | grep -v *shim* | grep -e '^[Zz]' | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1"`

**Comment by yuzhiquan** [comment]
> Can we get around it by adding filter conditions to this command? such as: `ps -A -ostat,ppid,cmd | grep -v *shim* | grep -e '^[Zz]' | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1"`

May be the fix can avoid this issue, but z process does not affect in many situation, so i'm not sure if flannel or dns pod make z process, for example, this cmd can handle these?

**Comment by pixiake** [comment]
> > Can we get around it by adding filter conditions to this command? such as: `ps -A -ostat,ppid,cmd | grep -v *shim* | grep -e '^[Zz]' | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1"`
> 
> May be the fix can avoid this issue, but z process does not affect in many situation, so i'm not sure if flannel or dns pod make z process, for example, this cmd can handle these?

Yes, some zombie processes may be killed by mistake.

**Pull request merged**
