### PR TITLE
fix: fix ubuntu debian chrony bug

### PR DESCRIPTION
**Pull request by kuops**
### What type of PR is this?

/kind bug

### What this PR does / why we need it:

fix: chrony service name and config path in ubuntu and debian is diffrent to centos

### Which issue(s) this PR fixes:

Fixes # [1414](https://github.com/kubesphere/kubekey/issues/1414)

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by 24sama** [comment]
Hi @kuops, thanks for your contributions!

**Comment by pixiake** [comment]
@all-contributors please add @kuops  for code

**Comment by pixiake** [comment]
@all-contributors please add @kuops for code

**Pull request merged**
