### PR TITLE
kubekey support kubeovn network plugin with kube-ovn v1.5.0

### PR DESCRIPTION
**Pull request by fafucoder**

### CODE REVIEW

**Comment by fafucoder** [comment]
Kubekey support kubeovn with version 1.5.0 for more information can refer [kube-ovn](https://github.com/alauda/kube-ovn)

**Comment by pixiake** [comment]
@fafucoder Thanks for the contribution.

**Comment by FeynmanZhou** [comment]
@fafucoder @pixiake Is there any documentation of installing Kubernetes and Kube-OVN using Kubekey?

**Comment by fafucoder** [comment]
@FeynmanZhou The quick way to use is to change the network plugin name to kubeovn, 
image

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou The quick way to use is to change the network plugin name to kubeovn
> image

Only one configuration as follows?

```
network:
   plugin: kubeovn
   calico:
      ···
```

**Pull request merged**
