### PR TITLE
Update tools.go

### PR DESCRIPTION
**Pull request by sbhnet**
add hack tools.go import code-generator/cmd files

### CODE REVIEW

**Comment by sbhnet** [comment]
add hack tools.go import code-generator/cmd files

**Comment by sbhnet** [comment]
add hack tools.go import code-generator/cmd files  Signed-off-by  sbhnet

**Comment by pixiake** [comment]
@all-contributors please add @sbhnet  for code

**Comment by FeynmanZhou** [comment]
@sbhnet Thanks for your contribution! Feel free to join and connect with us on Slack or WeChat group, you can find the entry point on [KubeSphere website](https://kubesphere.io/).

**Pull request merged**
