### PR TITLE
support kk add and delete node with master role

### PR DESCRIPTION
**Pull request by wenwenxiong**
### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wenwenxiong** [comment]
kk from single node to multi node,can not add master node and use kube-vip loadbalancer in default ; in the other hand, kk can not delete node with master role, the single node to multi node and multi node to single node is exist. with the pr, we can add and delete node with master role.

**Comment by littleBlackHouse** [comment]
@all-contributors please add @wenwenxiong  for code

**Pull request merged**
